on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write # Required for Reviewdog and PR-Agent to comment on PRs
  checks: write

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    # needs: linter-inline-review
    if: ${{ always() }} # <--- Ensure AI review runs even if the linter fails
    steps:
      - name: Run PR-Agent Review
        uses: the-pr-agent/pr-agent@main # <--- Fixes 'repository not found'
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_action_config: |
            auto_describe: true
            auto_review: true
            auto_improve: true